export const TOGGLE_MENU = "TOGGLE_MENU";

export const GET_ELEMENTS = "GET_ELEMENTS";
export const SEARCH_ELEMENTS = "SEARCH_ELEMENTS";
export const SET_ELEMENTAL_STATE = "SET_ELEMENTAL_STATE";

export const GET_THEME = "GET_THEME";
export const SET_THEME = "SET_THEME";

export const SET_TEMP_UNIT = "SET_TEMP_UNIT";

export const SET_DISPLAY_VALUE = "SET_DISPLAY_VALUE";